[workspace]
default-members = ["robot_operations"]
members = ["models", "robot_operations"]
resolver = "2"

[workspace.dependencies]
sea-orm = { version = "0.12.14", features = [
    "runtime-tokio-rustls",
    "sqlx-mysql",
] }
